#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MAINMENU                            152
#define IDD_BANIP                               154
#define IDD_BANLIST                             155
#define IDD_CHANGEMAP                           157
#define IDD_EDITBAN                             159
#define IDD_MAPROTATION                         163
#define IDD_SERVERDIALOG                        166
#define IDD_SERVERSTATISTICS                    168
#define IDD_DMFLAGS_COOP                        501
#define IDD_DMFLAGS_DM                          503
#define IDD_DMFLAGS                             504
#define IDD_DMFLAGS_GENERAL                     506
#define IDD_DMFLAGS_COMPAT                      508
#define IDD_DMFLAGS_PLAYERS                     511
#define IDD_BANPLAYER_SIMPLE                    512
#define IDD_DMFLAGS_LMS                         513
#define IDD_BANPLAYER_ADV                       514
#define IDD_SERVERSETTINGS_SERVERTAB            515
#define IDD_SERVERSETTINGS_GAMEPLAYTAB          516
#define IDD_SERVERSETTINGS_ACCESSTAB            518
#define IDD_SERVERSETTINGS_DIALOG               519
#define IDD_SERVERSETTINGS_ADMINTAB             520
#define IDD_MESSAGEOPTIONS                      522
#define IDD_EDITMOTD                            524
#define IDI_ICOSETTINGS                         527
#define IDC_SHOWFLAGS                           1000
#define IDC_TITLE                               1000
#define IDC_ADDMAP                              1001
#define IDC_MAPMODE                             1001
#define IDC_SETTINGSTAB                         1001
#define IDC_SPIN1                               1010
#define IDC_BANBOX                              1049
#define IDC_BANFILE                             1049
#define IDC_INPUTBOX                            1049
#define IDC_IPADDRESS                           1049
#define IDC_LOGFILE                             1049
#define IDC_MAPNAME                             1049
#define IDC_PASSWORD                            1049
#define IDC_REASON                              1049
#define IDC_BANLIST                             1054
#define IDC_MAPLISTBOX                          1054
#define IDC_PLAYERLIST                          1054
#define IDC_REMOVE                              1062
#define IDC_EDIT                                1071
#define IDC_SEND                                1071
#define IDC_BANCOMMENT                          1077
#define IDC_CLEAR                               1078
#define IDC_ENFORCEBANS                         1079
#define IDC_INTERMISSION                        1081
#define IDC_TITLEBOX                            1142
#define IDC_SCOREBOARD1                         1143
#define IDC_SCOREBOARD2                         1144
#define IDC_SCOREBOARD3                         1145
#define IDC_SCOREBOARD4                         1146
#define IDC_CONSOLEBOX                          1147
#define IDC_USEMAPROTATIONLIST                  1149
#define IDC_USERANDOMMAP                        1150
#define IDC_ENABLELOGGING                       1152
#define IDC_TIMESTAMPFORMAT                     1153
#define IDC_TIMESTAMP                           1154
#define IDC_STRIPCODES                          1155
#define IDC_DONOTSTRIPCODES                     1156
#define IDC_LEAVEINFORMAT                       1157
#define IDC_LMS_ALLOWCHAINSAW                   1158
#define IDC_LMS_ALLOWPISTOL                     1159
#define IDC_LMS_ALLOWSHOTGUN                    1160
#define IDC_LMS_ALLOWSSG                        1161
#define IDC_LMS_ALLOWCHAINGUN                   1162
#define IDC_LMS_ALLOWMINIGUN                    1163
#define IDC_LMS_ALLOWROCKETLAUNCHER             1164
#define IDC_LMS_ALLOWGRENADELAUNCHER            1165
#define IDC_LMS_ALLOWPLASMA                     1166
#define IDC_LMS_ALLOWRAILGUN                    1167
#define IDC_LMS_SPECTATORVIEW                   1168
#define IDC_LMS_SPECTATORTALK                   1169
#define IDC_REQUIREPW                           1173
#define IDC_REQUIREJOINPW                       1174
#define IDC_JOINPASSWORD                        1175
#define IDC_RCONPASSWORD                        1176
#define IDC_MAXCLIENTS                          1177
#define IDC_MAXPLAYERS                          1178
#define IDC_SPIN6                               1181
#define IDC_MOTD                                1182
#define IDC_UPDATEMASTER                        1184
#define IDC_BROADCAST                           1185
#define IDC_SERVERNAME                          1188
#define IDC_WADURL                              1189
#define IDC_EMAIL                               1190
#define IDC_GAMEPLAYMODE                        1191
#define IDC_SKILL                               1192
#define IDC_BOTSKILL                            1193
#define IDC_FRAGLIMIT                           1194
#define IDC_TIMELIMIT                           1195
#define IDC_POINTLIMIT                          1196
#define IDC_DUELLIMIT                           1197
#define IDC_WINLIMIT                            1198
#define IDC_MAXLIVES                            1199
#define IDC_AVGNUMPLAYERS                       1205
#define IDC_MAXPLAYERSATONETIME                 1206
#define IDC_TOTALFRAGS                          1207
#define IDC_TOTALUPTIME                         1208
#define IDC_TOTALINBOUNDDATATRANSFER            1209
#define IDC_TOTALOUTBOUNDDATATRANSFER           1210
#define IDC_AVERAGEINBOUNDDATATRANSFER          1211
#define IDC_AVERAGEOUTBOUNDDATATRANSFER         1212
#define IDC_PEAKINBOUNDDATATRANSFER             1213
#define IDC_PEAKOUTBOUNDDATATRANSFER            1214
#define IDC_CURRENTINBOUNDDATATRANSFER          1215
#define IDC_CURRENTOUTBOUNDDATATRANSFER         1216
#define IDC_PWADS                               1222
#define IDC_BARRELS_RESPAWN                     2027
#define IDC_COMPATF_BOOMSCROLL                  2036
#define IDC_COMPATF_DEHHEALTH                   2037
#define IDC_COMPATF_DROPOFF                     2038
#define IDC_COMPATF_INVISIBILITY                2039
#define IDC_COMPATF_RAVENSCROLL                 2040
#define IDC_COMPATF_SOUNDTARGET                 2041
#define IDC_COMPATF_TRACE                       2042
#define IDC_COOP_HALVE_AMMO                     2045
#define IDC_COOP_LOSE_AMMO                      2046
#define IDC_COOP_LOSE_ARMOR                     2047
#define IDC_COOP_LOSE_INVENTORY                 2048
#define IDC_COOP_LOSE_POWERUPS                  2049
#define IDC_DISABLESTEALTHMONSTERS              2064
#define IDC_FAST_MONSTERS                       2084
#define IDC_FORCE_RESPAWN                       2087
#define IDC_INFINITE_AMMO                       2095
#define IDC_INSTANTRESPAWN                      2099
#define IDC_ITEMS_RESPAWN                       2103
#define IDC_LIMITED_AIRMOVEMENT                 2107
#define IDC_LIMITPAIN                           2108
#define IDC_LOSE_KEYS                           2125
#define IDC_LOSE_WEAPONS                        2126
#define IDC_MONSTERS_RESPAWN                    2137
#define IDC_NO_COOP_MP_WEAPON_SPAWN             2142
#define IDC_NO_FOV                              2144
#define IDC_NO_FREELOOK                         2145
#define IDC_NO_PASSMOBJ                         2150
#define IDC_NO_RESPAWN_INVUL                    2151
#define IDC_NODOORLIGHT                         2155
#define IDC_NOTOSSDROPS                         2156
#define IDC_OLDINTERMISSION                     2157
#define IDC_ORIGINALSOUNDCURVE                  2158
#define IDC_PLASMA_BUMP_BUG                     2162
#define IDC_RESPAWN_SUPER                       2178
#define IDC_SAME_SPAWN_SPOT                     2183
#define IDC_SHORTTEX                            2195
#define IDC_SHOTGUN_START                       2196
#define IDC_DF2_YES_KEEP_FRAGS                  2233
#define IDC_DF2_NO_RESPAWN                      2251
#define IDC_DF2_YES_LOSEFRAG                    2252
#define IDC_DF2_INFINITE_INVENTORY              2253
#define IDC_DF2_KILL_MONSTERS                   2254
#define IDC_DF2_NO_AUTOMAP                      2255
#define IDC_DF2_NO_AUTOMAP_ALLIES               2256
#define IDC_DF2_DISALLOW_SPYING                 2257
#define IDC_DF2_CHASECAM                        2258
#define IDC_DF2_NOSUICIDE                       2259
#define IDC_DF2_NOAUTOAIM                       2260
#define IDC_ZADF_FORCE_GL_DEFAULTS              2261
#define IDC_ZADF_NO_ROCKET_JUMPING              2262
#define IDC_ZADF_FORCE_ALPHA                    2264
#define IDC_COMPATF_SILENT_INSTANT_FLOORS       2275
#define IDC_COMPATF_SECTORSOUNDS                2276
#define IDC_COMPATF_MISSILECLIP                 2277
#define IDC_COMPATF_CROSSDROPOFF                2278
#define IDC_COMPATF_OLDRADIUSDMG                2279
#define IDC_COMPATF_NO_CROSSHAIR                2280
#define IDC_COMPATF_OLD_WEAPON_SWITCH           2281
#define IDC_ZACOMPATF_NETSCRIPTS_ARE_CLIENTSIDE 2284
#define IDC_DMF_JUMPING                         2286
#define IDC_DMF_CROUCHING                       2288
#define IDC_FALLINGDAMAGE                       2289
#define IDC_ZADF_AWARD_DAMAGE_INSTEAD_KILLS     2290
#define IDC_SPAWN_FARTHEST                      2300
#define IDC_STAIRINDEX                          2305
#define IDC_USEBLOCKING                         2318
#define IDC_WALLRUN                             2323
#define IDC_YES_DEGENERATION                    2334
#define IDC_YES_DOUBLEAMMO                      2335
#define IDC_YES_FREEAIMBFG                      2336
#define IDC_YES_WEAPONDROP                      2337
#define IDC_FLAGSTABCONTROL                     2421
#define IDC_NO_TEAM_SWITCH                      2423
#define IDC_NO_TEAM_SELECT                      2424
#define IDC_INSTANT_RETURN                      2425
#define IDC_ZADF_YES_KEEP_TEAMS                 2426
#define IDC_DISABLETAUNTS                       2429
#define IDC_WEAPONS_STAY                        2432
#define IDC_NO_RUNES                            2433
#define IDC_NO_MONSTERS                         2434
#define IDC_NO_ARMOR                            2435
#define IDC_MAGICSILENCE                        2436
#define IDC_SILENTPICKUP                        2437
#define IDC_DMF_EXIT1                           2438
#define IDC_NO_HEALTH1                          2440
#define IDC_COMPATFLAGS_VALUE                   2445
#define IDC_COMPATFLAGS2_VALUE                  2446
#define IDC_DMFLAGS_VALUE                       2447
#define IDC_DMFLAGS2_VALUE                      2448
#define ID_FILE_EXIT                            4003
#define ID_SETTINGS_GENERALSETTINGS             4004
#define ID_SETTINGS_CONFIGREDMFLAGS             4005
#define ID_SETTINGS_MAPROTATION                 4006
#define ID_SERVER_STATISTICS                    4010
#define ID_ADMIN_KICKBAN                        4014
#define ID_ADMIN_VIEWBANLIST                    4015
#define ID_ADMIN_BANIP                          4016
#define ID_ADMIN_CHANGEMAP                      4017
#define IDC_HISTORY                             4049
#define IDC_TRAFFICIN                           4053
#define IDC_BANDESCRIPTION                      4055
#define IDC_TRAFFICOUT                          4055
#define IDC_BANLENGTH                           4057
#define IDC_CHANGEBANLENGTH                     4058
#define IDC_ALLOW_CALLVOTE                      4060
#define IDC_ALLOWVOTE_SPECTATOR                 4061
#define IDC_ALLOWVOTE_DUELLIMIT                 4062
#define IDC_ALLOWVOTE_FRAGLIMIT                 4063
#define IDC_ALLOWVOTE_KICKLIMIT                 4064
#define IDC_ALLOWVOTE_POINTLIMIT                4065
#define IDC_ALLOWVOTE_TIMELIMIT                 4066
#define IDC_ALLOWVOTE_WINLIMIT                  4067
#define IDC_ALLOWVOTE_MAP                       4068
#define IDC_MARKCHATLINES                       4069
#define IDC_ALLOWRCON                           4070
#define IDC_LOGFILENAME_TIMESTAMP               4072
#define IDC_VIEWLOGFILE                         4082
#define ID_ADMIN_ADDREMOVEBOT                   40000
#define IDC_LMSWEAPONS_VALUE                    40001
#define IDR_JOIN_SERVER                         40001
#define IDC_DUELLIMITSPIN                       40002
#define IDC_LMSSPECTATORS_VALUE                 40002
#define IDM_NOBODY_CAN_SEE_MY_SERVER_1          40002
#define IDC_DUELLIMIT_LABEL                     40003
#define IDM_HOW_TO_USE1                         40003
#define IDC_WINLIMITSPIN                        40004
#define IDM_COMMAND_REFERENCE1                  40004
#define IDC_WINLIMIT_LABEL                      40005
#define IDM_GAME_MODES1                         40005
#define IDC_POINTLIMITSPIN                      40006
#define IDM_DMFLAGS1                            40006
#define IDC_POINTLIMIT_LABEL                    40007
#define IDC_FRAGLIMITSPIN                       40008
#define IDC_FRAGLIMIT_LABEL                     40009
#define IDC_TIMELIMITSPIN                       40010
#define IDC_MAPLIST                             40011
#define IDC_MODIFIER                            40012
#define IDC_MAXLIVESSPIN                        40013
#define IDC_MAXLIVES_LABEL                      40014
#define IDC_WADURLLABEL                         40016
#define IDC_PWADGROUP                           40018
#define IDC_STARTUPMESSAGE                      40019
#define IDC_MESSAGES                            40021
#define IDC_SCOREBOARDW                         40021
