// 10af1739daa34a45cb0817adfdef4106b20c0634+
//
// This file was automatically generated by the
// updaterevision tool. Do not edit by hand.

#define GIT_DESCRIPTION "ZA_2.1.2-852-10af1739daa3"
#define GIT_HASH "10af1739daa34a45cb0817adfdef4106b20c0634+"
#define GIT_TIME "2019-10-13 21:38:53 +0200"
#define HG_REVISION_NUMBER 1570995533
#define HG_REVISION_HASH_STRING "10af1739daa3"
#define HG_TIME "191013-1938M"
